spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.164.209:3306/xling?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456


server:
  port: 8094

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.guet.weappdemo.bean
